### ISSUE TITLE
Spelling & Grammar fixes

### ISSUE THREAD

**Issue by sgalla1** [diggerhq/docs-site#1]
In the intro (https://github.com/diggerhq/docs-site/blob/master/docs/README.md) file there are some small errors in the How it Works section:

Digger is your swiss-army knife for setting up, deploying and monitoring your infrastructure. We are starting with containerised apps but there is ~alot~ (a lot) more features in the pipeline. We like to think of Digger as the glue that connects your app to the underlying infrastructure it needs to run on. ~Lets~ (Let's; Let us) take a quick example of a container that needs to run on AWS. You have the choice of deploying it directly to EC2, or AWS ECS or AWS EKS. And under AWS ECS there is multiple options such as ECS classic or ECS fargate.

You also have to ~chose~ (choose) a registry to host your image, examples **(include)** dockerhub or Amazon ECR. Once you have made decisions about registry and target (ECS), you then need to architect your system including VPCs, security groups, roles and ~loadbalancer~ (load balancer). Next you need to setup the resources which your service requires like RDS, a Queue, Email service etc.

Digger heavylifts these decisions for you by offering a library of opinionated targets to chose from. In other words, you ~had~ (hand) us your container and we will take care of setting up your infrastructure. But we don't stop here. Digger will also take care of exposing the right environment ~varaibles~ (variables) ~in your~ so your app works out of the box. Digger then controls your release cycle so you can build-push-release also using digger commands!

**Comment by motatoes** [comment]
Thanks for reporting this @sgalla1 ! Will be deployed with fixes shortly :)
